### PR TITLE
C++ compile_cmd values in seeds.rb fixed

### PR DESCRIPTION
**Pull request by alan-navarro96**

### CODE REVIEW

**Comment by hermanzdosilovic** [comment]
@alan-navarro96 thanks! :smile:

**Comment by hermanzdosilovic** [comment]
@alan-navarro96 I have deployed your changes to both: [api.judge0.com](http://api.judge0.com/) and [t0.api.judge0.com](http://t0.api.judge0.com/).

**Comment by alan-navarro96** [comment]
Hey Herman, I'm trying to send a submission but the judge is not working?
Do you know why?

Thanks for answering,
Alan Navarro

**Comment by hermanzdosilovic** [comment]
Hi @alan-navarro96, I don't know what kind of issue you had, but now judge is working. Please try again. Maybe there was some network issue.

**Pull request merged**
